server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:file:./spring-boot-h2-db;MODE=MySQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  sql.init.mode: always
  
project:
  name: postarticle
  version: 0.1
  description: technical test
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
